[workspace]
members = [
    "minecraft-protocol",
    "minecraft-protocol-derive",
    "minecraft-server",
    "minecraft-entities",
    "minecraft-positions",
    "tags-macros"
]

workspace.resolver = "2"
