[workspace]
members = [
    "minecraft-protocol",
    "minecraft-protocol-derive",
    "minecraft-server",
    "minecraft-entities",
    "minecraft-entities-derive",
    "minecraft-positions"
]

workspace.resolver = "2"
