[package]
name = "minecraft-entities-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6"
proc-macro-error = "1.0.4"
quote = "1.0"
proc-macro2 = "1.0"
